#!/usr/bin/env bash

set -euo pipefail

main() {
    osacompile -o /dev/null "${0%/*}"/../../bin/toggle_wifi
    osacompile -o /dev/null "${0%/*}"/../../bin/setup_ducky
    local -r GREEN='\033[0;32m'
    local -r RESET='\033[0m'
    # shellcheck disable=SC2059
    printf "${GREEN}✔︎${RESET} applescripts compiled successfully\n"
}

main
