#!/usr/bin/env bash

set -eo pipefail

configure_git_user() {
    local -r GIT_EMAIL=$1
    git config --file ~/.gitconfig.local user.email "$GIT_EMAIL"
    gpg --list-secret-keys --keyid-format LONG\
        | grep -B 2 "$GIT_EMAIL"\
        | head -n1\
        | cut -d/ -f2\
        | cut -d' ' -f1\
        | xargs git config --file ~/.gitconfig.local user.signingkey
}

import_gpg_private_key() {
    local -r GIT_EMAIL=$1
    read -r -p "Enter 1Password email: " OP_EMAIL
    read -r -p "Enter 1Password secret key: " OP_SECRET_KEY
    eval "$(op signin my "$OP_EMAIL" "$OP_SECRET_KEY")"

    local -r UUID=$(op list items | jq --raw-output --arg GIT_EMAIL "$GIT_EMAIL" '.[] | select(.overview.url==$GIT_EMAIL and .overview.title=="GPG Private Key") | .uuid')
    echo -e "$(op get item "$UUID" | jq -r '.details.password')" | gpg --import
}

configure_gpg_agent() {
    local -r DIR=~/.gnupg
    if [[ ! -e $DIR/gpg-agent.conf ]]; then
        mkdir -p $DIR
        {
            # 30 days
            echo "default-cache-ttl 2592000"
            echo "max-cache-ttl 2592000"
        } > $DIR/gpg-agent.conf
    fi
    gpgconf --kill gpg-agent
}

main() {
    stow --verbose=2 git

    read -r -p "Enter git email: " GIT_EMAIL

    import_gpg_private_key "$GIT_EMAIL"
    configure_git_user "$GIT_EMAIL"
    configure_gpg_agent
}

main
