#!/usr/bin/env bash

set -euo pipefail

main() {
    local -r FILE=$(realpath "${0%/*}/../../moom/config.plist")
    defaults import com.manytricks.Moom "$FILE"
    echo "Successfully imported config"
}

main


