#!/usr/bin/env bash

set -euo pipefail

main() {
    code --install-extension shan.code-settings-sync
    local -r GIST_ID="5a7dd29b572f5fb1623a61c815e5865a"
    echo $GIST_ID | pbcopy
    echo "Gist ID copied to clipboard."
    open https://gist.github.com/alexpyoung/$GIST_ID
    open https://github.com/shanalikhan/code-settings-sync#download-your-settings
    open https://github.com/shanalikhan/code-settings-sync#toggle-auto-upload-on-change
    open https://github.com/shanalikhan/code-settings-sync#toggle-auto-download
}

main
