#!/usr/bin/env bash

set -euo pipefail

main() {
    local -r FILE=$(realpath "${0%/*}/../../moom/config.plist")
    echo "Generating plist..."
    defaults export com.manytricks.Moom "$FILE"
    git diff
}

main

