#!/usr/bin/env bash

set -euo pipefail

own() {
    sudo mkdir -p /usr/local/"$1"
    sudo chown -R "$(whoami)":admin /usr/local/"$1"
}

install_homebrew() {
    if [[ ! -e /usr/local/homebrew ]]; then
        echo "Installing homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
    # https://github.com/Homebrew/brew/issues/3228
    own homebrew
    own var/homebrew
}

main() {
    install_homebrew
    local -r FILE=$(realpath "${0%/*}/../../Brewfile")
    echo "Installing packages..."
    brew bundle install --no-lock --file "$FILE"
}

main
