name: CI
on: push
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y shellcheck
    - uses: actions/checkout@v2
    - run: scripts/ci/shellcheck
  osacompile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: scripts/ci/osacompile
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - run: pip install --upgrade pylint requests
    - uses: actions/checkout@v2
    - run: scripts/ci/pylint
