name: CI
on:
  push:
    branches:
      - master
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: bin/cibuild
  bootstrap:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install stow
      - run: bin/bootstrap/vim
      - run: bin/bootstrap/zsh
